# Generated by Django 3.0 on 2020-03-02 18:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('body_en', wagtail.core.fields.RichTextField(blank=True, default='', null=True)),
                ('body_de', wagtail.core.fields.RichTextField(blank=True, default='', null=True)),
                ('body_fr', wagtail.core.fields.RichTextField(blank=True, default='', null=True)),
                ('body_it', wagtail.core.fields.RichTextField(blank=True, default='', null=True)),
                ('body_es', wagtail.core.fields.RichTextField(blank=True, default='', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
