# Generated by Django 3.0 on 2020-03-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200302_1827'),
    ]

    operations = [
       
    ]
