# Generated by Django 3.0 on 2020-03-02 19:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200302_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='transhomepage',
            name='footer',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transhomepage',
            name='footer_ar',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transhomepage',
            name='footer_en',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transhomepage',
            name='footer_es',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transhomepage',
            name='footer_fr',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transhomepage',
            name='footer_po',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
