# Generated by Django 3.0 on 2020-04-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200302_1927'),
    ]

    operations = [
        
    ]
