# Generated by Django 3.0.5 on 2020-04-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200302_1927'),
    ]

    operations = [
       
    ]
