# Generated by Django 3.0.5 on 2020-04-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200302_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transhomepage',
            old_name='body_po',
            new_name='body_pt',
        ),
        migrations.RenameField(
            model_name='transhomepage',
            old_name='footer_po',
            new_name='footer_pt',
        ),
    ]
