# Generated by Django 3.0.5 on 2020-05-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200430_1923'),
        ('home', '0006_auto_20200430_1426'),
    ]

    operations = [
    ]
