# Generated by Django 3.0 on 2020-05-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20200502_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transhomepage',
            old_name='body_de',
            new_name='body_ar',
        ),
        migrations.RenameField(
            model_name='transhomepage',
            old_name='body_it',
            new_name='body_pt',
        ),
        migrations.RenameField(
            model_name='transhomepage',
            old_name='footer_po',
            new_name='footer_pt',
        ),
    ]
